#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export test=true dev=false port=0000
export db_user=postgres
export db_name=_
export db_pass=EMP!2021
export db_host=52.163.80.13
export db_port=5432
export db_dialect=postgres

npx nx run-many --target=test --all